//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAS.DataStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStore()
        {
            this.tblConsultant = new HashSet<tblConsultant>();
        }
    
        public int st_Id { get; set; }
        public string st_Name { get; set; }
        public string st_Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConsultant> tblConsultant { get; set; }
    }
}
